'use client';

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { ShieldCheck, ShieldAlert, ShieldX, Users, Bot, Briefcase, UserCog, CheckCircle, XCircle, AlertTriangle, Brain } from 'lucide-react';

// Data for the Kanban-style role cards
const roleGuidance = [
  {
    role: "Sales Reps",
    icon: <Users className="h-8 w-8 text-blue-500" />,
    guidance: {
      green: [
        "Use AI to draft introductory emails and follow-ups.",
        "Generate summaries of long sales reports to identify key trends.",
        "Optimize daily travel routes for client visits.",
        "Prepare for meetings by asking AI for company overviews and talking points."
      ],
      orange: [
        "Always double-check AI-generated product specifications or pricing for accuracy before sending to a client.",
        "Personalize AI-drafted emails to maintain your authentic voice and relationship with the client.",
        "Be cautious using AI to analyze sales data with personal customer information."
      ],
      red: [
        "Never input confidential client contact lists or sensitive commercial terms into public AI tools.",
        "Do not promise clients features or delivery times based solely on AI-generated information.",
        "Avoid using AI to create legally binding contract clauses."
      ]
    }
  },
  {
    role: "Marketing",
    icon: <Bot className="h-8 w-8 text-pink-500" />,
    guidance: {
      green: [
        "Brainstorm social media campaigns, blog post ideas, and ad copy.",
        "Generate different versions of marketing copy to A/B test.",
        "Create outlines and first drafts for internal marketing reports.",
        "Analyze marketing campaign data to identify high-performing content."
      ],
      orange: [
        "Ensure all AI-generated content is reviewed by a human to match d3's brand voice and tone.",
        "Verify any statistics or factual claims generated by AI before publishing.",
        "Be mindful of copyright when using AI to generate images or logos."
      ],
      red: [
        "Never use AI to generate entire articles or blog posts without significant human editing and oversight.",
        "Do not publish AI-generated content that makes unsubstantiated claims about products.",
        "Avoid inputting unreleased product information or strategic marketing plans into public AI tools."
      ]
    }
  },
  {
    role: "Admin & Operations",
    icon: <Briefcase className="h-8 w-8 text-orange-500" />,
    guidance: {
      green: [
        "Draft internal communications, meeting agendas, and summaries.",
        "Organize and categorize data from spreadsheets.",
        "Use AI to create templates for standard operating procedures (SOPs).",
        "Summarize long email chains to get the key action points."
      ],
      orange: [
        "Always verify important details like dates, names, and figures in AI-summarized documents.",
        "When drafting internal comms, ensure the tone is appropriate for the audience.",
        "Use caution when asking AI to handle scheduling to avoid errors."
      ],
      red: [
        "Never input employee PII (Personally Identifiable Information) like addresses or IRD numbers into public AI.",
        "Do not process invoices or financial transactions based solely on AI data extraction without verification.",
        "Avoid using AI for any HR-related disciplinary or performance review documentation."
      ]
    }
  },
  {
    role: "Management",
    icon: <UserCog className="h-8 w-8 text-purple-500" />,
    guidance: {
      green: [
        "Analyze market trends and competitor reports summarized by AI.",
        "Draft frameworks for strategic plans, presentations, and board updates.",
        "Use AI as a brainstorming partner for new business initiatives.",
        "Condense user reports and feedback into high-level themes."
      ],
      orange: [
        "Treat AI-generated strategic insights as a starting point for discussion, not a final decision.",
        "Ensure any data used for strategic analysis is anonymized before inputting into an AI tool.",
        "Be aware of potential biases in AI-generated reports."
      ],
      red: [
        "Never make final hiring, firing, or financial decisions based solely on an AI recommendation.",
        "Do not input confidential company financial data or unannounced merger/acquisition info into public AI.",
        "Avoid using AI to write sensitive communications to shareholders or the board without thorough review."
      ]
    }
  }
];

export default function PlaybookPage() {
  return (
    <div className="py-8">
      <header className="mb-12 text-center">
        <h1 className="text-5xl font-extrabold tracking-tight text-primary text-gradient">AI Guidelines & Usage Policy</h1>
        <p className="mt-4 text-lg text-muted-foreground max-w-3xl mx-auto">
          Your official guide to using AI safely, effectively, and responsibly at d3.
        </p>
      </header>

      <div className="max-w-7xl mx-auto">
        <section className="mb-12">
            <Card className="p-8 bg-muted/50">
                <CardHeader className="text-center">
                    <CardTitle className="text-4xl">Our Core Principles</CardTitle>
                </CardHeader>
                <CardContent>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-center">
                        <div className="flex flex-col items-center border bg-card text-card-foreground shadow-sm rounded-lg p-6 h-full">
                            <ShieldCheck className="h-12 w-12 text-green-500 mb-4" />
                            <h3 className="font-semibold text-xl mb-2">Enhance, Don't Replace</h3>
                            <p className="text-muted-foreground">AI is a tool to augment your skills and creativity, not to replace human judgment.</p>
                        </div>
                         <div className="flex flex-col items-center border bg-card text-card-foreground shadow-sm rounded-lg p-6 h-full">
                            <Brain className="h-12 w-12 text-blue-500 mb-4" />
                            <h3 className="font-semibold text-xl mb-2">Be Human-Centric</h3>
                            <p className="text-muted-foreground">Focus on how AI can solve real-world problems for our customers and our team.</p>
                        </div>
                        <div className="flex flex-col items-center border bg-card text-card-foreground shadow-sm rounded-lg p-6 h-full">
                            <ShieldAlert className="h-12 w-12 text-yellow-500 mb-4" />
                            <h3 className="font-semibold text-xl mb-2">Security First</h3>
                            <p className="text-muted-foreground">Protecting company, client, and employee data is our top priority.</p>
                        </div>
                        <div className="flex flex-col items-center border bg-card text-card-foreground shadow-sm rounded-lg p-6 h-full">
                            <ShieldX className="h-12 w-12 text-red-500 mb-4" />
                            <h3 className="font-semibold text-xl mb-2">Accountability Matters</h3>
                            <p className="text-muted-foreground">You are ultimately responsible for the final output and accuracy of any work produced with AI.</p>
                        </div>
                    </div>
                </CardContent>
            </Card>
        </section>

        <Separator className="my-12" />

        <section className="mb-12">
            <header className="text-center mb-10">
                <h2 className="text-3xl font-semibold">Role-Specific Guidance</h2>
                <p className="text-muted-foreground mt-2">Practical do's and don'ts for your team.</p>
            </header>
            <div className="grid md:grid-cols-2 gap-8">
                {roleGuidance.map(roleItem => (
                    <Card key={roleItem.role} className="flex flex-col">
                        <CardHeader className="flex flex-row items-center gap-4">
                            {roleItem.icon}
                            <CardTitle className="text-2xl">{roleItem.role}</CardTitle>
                        </CardHeader>
                        <CardContent className="flex-grow space-y-6">
                            {/* Green Light */}
                            <div>
                                <div className="flex items-center gap-2 mb-2">
                                    <CheckCircle className="h-6 w-6 text-green-500" />
                                    <h4 className="font-semibold text-lg text-green-600">Do's (Green Light)</h4>
                                </div>
                                <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
                                    {roleItem.guidance.green.map(item => <li key={item}>{item}</li>)}
                                </ul>
                            </div>
                             {/* Orange Light */}
                            <div>
                                <div className="flex items-center gap-2 mb-2">
                                    <AlertTriangle className="h-6 w-6 text-yellow-500" />
                                    <h4 className="font-semibold text-lg text-yellow-600">Cautions (Orange Light)</h4>
                                </div>
                                <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
                                    {roleItem.guidance.orange.map(item => <li key={item}>{item}</li>)}
                                </ul>
                            </div>
                             {/* Red Light */}
                            <div>
                                <div className="flex items-center gap-2 mb-2">
                                    <XCircle className="h-6 w-6 text-red-500" />
                                    <h4 className="font-semibold text-lg text-red-600">Don'ts (Red Light)</h4>
                                </div>
                                <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
                                    {roleItem.guidance.red.map(item => <li key={item}>{item}</li>)}
                                </ul>
                            </div>
                        </CardContent>
                    </Card>
                ))}
            </div>
        </section>

        <Separator className="my-12" />

        <section className="text-center">
            <h2 className="text-3xl font-semibold mb-4">Have Questions?</h2>
            <p className="text-muted-foreground mb-6">If you're unsure about a specific use case, your first point of contact is your line manager or our designated CAIO, Carey Burt.</p>
            <a href="/dashboard/your-ai-report">
                <Button>Go to Reporting Page</Button>
            </a>
        </section>
      </div>
    </div>
  );
}